version: "3.9"
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN:-change-me}
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped

